services:
  postgres:
    image: postgres:16-alpine
    container_name: fitness_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
    volumes:
      - fitness_pg_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  fitness_pg_data:

